# Generated by Django 4.2.7 on 2024-01-06 09:07

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManagerPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read_filebrowser', 'Can read file browser'), ('can_write_filebrowser', 'Can write to file browser'), ('can_delete_filebrowser', 'Can delete in file browser'), ('can_change_filebrowser', 'Can change in file browser')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('orientation', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='L', max_length=1)),
                ('page_size', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('Letter', 'Letter'), ('Legal', 'Legal'), ('Ledger', 'Ledger')], default='A4', max_length=6)),
                ('html_template', models.TextField()),
                ('python_script', models.TextField()),
                ('python_validation_script', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('input_args', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('G', 'Generated'), ('D', 'Deleted')], default='P', max_length=1)),
                ('output_content', models.TextField(blank=True)),
                ('output_file', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('orientation', models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape')], default='L', max_length=1)),
                ('page_size', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('Letter', 'Letter'), ('Legal', 'Legal'), ('Ledger', 'Ledger')], default='A4', max_length=6)),
                ('html_template', models.TextField()),
                ('python_script', models.TextField()),
                ('python_validation_script', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical template',
                'verbose_name_plural': 'historical templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('optional', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.template')),
            ],
        ),
    ]
