# Generated by Django 4.2.11 on 2024-06-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltemplate',
            name='database',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.database'),
        ),
        migrations.AddField(
            model_name='template',
            name='database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='database',
            name='backend',
            field=models.CharField(choices=[('MS', 'MSSQL'), ('PG', 'Posgres')], default='MS', max_length=2),
        ),
    ]
