# Generated by Django 4.2.11 on 2024-06-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_template_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.database'),
        ),
    ]
