# Generated by Django 4.2.11 on 2024-07-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_template_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='backend',
            field=models.CharField(choices=[('MS', 'MSSQL'), ('PG', 'Postgres'), ('MY', 'MySQL'), ('MA', 'MariaDB')], default='MS', max_length=2),
        ),
    ]
