# Generated by Django 4.2.11 on 2024-07-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_database_backend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileManagerPermissions',
        ),
    ]
